# Get all users
GET http://localhost:3000/users

# Get a specific user
GET http://localhost:3000/users/2

# Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "John Doe ultimo agregado",
  "email": "johndoe@example.com",
  "roleId" : 1
}

# Update a user
PUT http://localhost:3000/users/3
Content-Type: application/json

{
  "name": "John Doe updated",
  "email": "nuevoemail@gmail.com",
    "roleId" : 20
}

# Delete a user
DELETE http://localhost:3000/users/3
